### ISSUE TITLE
Getting ENOENT error with gifsicle in my build

### ISSUE THREAD

**Issue by stewx** [imagemin/imagemin-gifsicle#13]
I'm using:
node 4.5.0
npm 2.15.9
imagemin 5.2.2
imagemin-gifsicle 5.1.0
Ubuntu 14.04 

In my Gulp build, using imagemin, I get the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: spawn /myproject/node_modules/gulp-imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by nstuyvesant** [comment]
Seems to happen when I use node >= 7.0. Reverting back to 6.9.2 resolved the issue for me.

**Comment by shinnn** [comment]
Remove `./node_modules` and install npm modules again.

**Comment by damianobarbati** [comment]
Neither working nor a solution.

**Comment by shuhikari** [comment]
@damianobarbati Are you using electron or webpack in the final build? 
Does it works in dev environment?

**Comment by damianobarbati** [comment]
@shuhikari the problem is actually the building from source happening on Alpine Linux (in docker image).

Any chance to have binaries shipped for that? 🙏🏻

**Comment by georginio** [comment]
# FROM node:10.15.1-alpine

# install apk dependencies (needed for image-webpack-loader)
RUN apk add --update \
    bash \
    lcms2-dev \
    libpng-dev \
    gcc \
    g++ \
    make \
    autoconf \
    automake \
  && rm -rf /var/cache/apk/*

Running this dependencies worked for me on docker, node:10.15.1-alpine since gifsicle is dependencie for image-webpack-loader

**Comment by bscheshirwork** [comment]
So. I use
```yml
  node:
    image: node:8.16.0
    volumes:
      - .:/var/www/html
```
instead of 
```yml
  node:
    image: node:8.16.0-alpone
    volumes:
      - .:/var/www/html
```
