### ISSUE TITLE
Compressing animated gif

### ISSUE THREAD

**Issue by adamjw3** [imagemin/imagemin-gifsicle#17]
Hi

I'm using https://github.com/gruntjs/grunt-contrib-imagemin and noticed that its not compressing animated gif's but if i run them through http://ezgif.com/optimize it does. is this a bug or am i missing a setting.

Thanks

**Comment by shinnn** [comment]
http://ezgif.com/optimize uses [giflossy](https://github.com/pornel/giflossy) that optimizes better than [gifsicle](https://github.com/kohler/gifsicle) does.

If https://github.com/kohler/gifsicle/pull/72 is merged, this plugin will optimize animated GIFs as much as giflossy does. Please wait for https://github.com/kohler/gifsicle/pull/72 to be merged.

**Comment by damianobarbati** [comment]
Is this working now? Because I still see animated gif not compressed at all. What setting should I apply?
