### ISSUE TITLE
Can't compress with gifsicle

### ISSUE THREAD

**Issue by pedrofracassi** [imagemin/imagemin-gifsicle#19]
Hello! I'm using this plugin to compress GIFs before sending them to a Telegram chat, because sadly telegram won't let bots send files bigger than 50MB.

The code i'm using is:
```javascript
imagemin([path], 'build/images', {use: [imageminGiflossy({lossy: 5})]}).then(() => {
        console.log('Done!');
        process.exit();
      });
```

And the response I'm getting is:
```
(node:9496) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Error in file: C:/Users/Pichau/Documents/GitHub/thegifmachine/file.gif

O sistema não pode encontrar o caminho especificado.
```
("O sistema não pode encontrar o caminho especificado" means "The system couldn't find the path specified".)

I don't know if this is a bug of I'm doing it wrong. The path is correct and I'm sure the file exists.

**Comment by kingjerod** [comment]
What is `path` equal to? Also, this module does not support the option `lossy` so that's not doing anything.

**Comment by 1000ch** [comment]
@pedrofracassi 
Please try the newest version of `imagemin` and `imagemin-gifsicle`. [The usage is slightly updated](https://github.com/imagemin/imagemin).
