### ISSUE TITLE
Need to change the width and height

### ISSUE THREAD

**Issue by hua1995116** [imagemin/imagemin-gifsicle#35]
Many time change the width and height is a good way to minify the images. If this suggestion is passed, I can provide a pr.

**Comment by Jeremboo** [comment]
I've found this fork that I'm gonna use for now: https://github.com/shahkashani/imagemin-giflossy/blob/master/package.json

With the width and height options implemented.

**Comment by 1000ch** [comment]
This suggestion might not be the responsibility of [gifsicle-bin](https://github.com/imagemin/gifsicle-bin) and its wrapper (this). Should be achieved outside of them.
