### ISSUE TITLE
readme.md errors

### ISSUE THREAD

**Issue by Gtskk** [imagemin/imagemin-gifsicle#4]
![image](https://cloud.githubusercontent.com/assets/2942038/9305220/0e95eee2-4522-11e5-84d6-fb52ced1c919.png)

An extra "()".

**Comment by shinnn** [comment]
`require('imagemin-gifsicle')()` doesn't return a stream instance but a constructor. https://github.com/imagemin/imagemin-gifsicle/blob/0d8dc383b0c9c56581e188d1e6391fec1fcefc3a/index.js#L11

**Comment by Gtskk** [comment]
Yes, my mistake.
