### ISSUE TITLE
Fail to optimize Gif Animated

### ISSUE THREAD

**Issue by xicond** [imagemin/imagemin-gifsicle#50]
-   Imagemin Version: 7.0.1
-   Imagemin Gifsicle Version: 6.0.1
-   Node Version: 12.21.0
-   NPM Version: 6.14.11
-   OS: OSX / Window 10

### Description:

Fail to optimize Gif Animated

```
Error: gifsicle:/private/var/folders/qd/d31kwps94kz4gyxrn_phyzgw0000gn/T/2bc53a32-def7-41d8-8407-e740a38fffb0:#22: read error: unknown block type 71 at file offset 32121
gifsicle:/private/var/folders/qd/d31kwps94kz4gyxrn_phyzgw0000gn/T/2bc53a32-def7-41d8-8407-e740a38fffb0:#21: read error: image corrupted, code out of range (20 times)
gifsicle:/private/var/folders/qd/d31kwps94kz4gyxrn_phyzgw0000gn/T/2bc53a32-def7-41d8-8407-e740a38fffb0:#21: read error: (not reporting more errors)
gifsicle:/private/var/folders/qd/d31kwps94kz4gyxrn_phyzgw0000gn/T/2bc53a32-def7-41d8-8407-e740a38fffb0:#21: read error: missing 98 pixels of image data
```

### Steps To Reproduce:
```
// app.js
const imagemin = require('imagemin');
const imageminGifsicle = require('imagemin-gifsicle');

(async () => {
	await imagemin(['images/*.gif'], {
		destination: 'build/images',
		plugins: [
			imageminGifsicle()
		]
	});

	console.log('Images optimized');
})();
```

Steps:

> curl [images/loading.gif](https://drive.google.com/file/d/1W4cJjYBqNxjlHpmqsosognb8G5Yy6dff/view?usp=sharing)

> node app.js

Is there a way to avoid animated gif

**Comment by 1000ch** [comment]
> Is there a way to avoid animated gif

For this purpose, [is-animated](https://github.com/qzb/is-animated) could work, but I'm not sure how it works for corrupted images. Then, you should fix the corrupted image first.
