### ISSUE TITLE
gifsicle vendor dependency missing

### ISSUE THREAD

**Issue by simonocaol** [imagemin/imagemin-gifsicle#8]
Hi,

My npm builds are failing because of a missing dependency in gifsicle.

Error: spawn /usr/src/app/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/vendor/gifsicle ENOENT

I've tried just installing imagemin-gifsicle and the dependency is still missing. I did globally install gifsicle and copied the vendor directory to my local dependencies which has allowed me to run builds. I'm running my builds in a docker container with the following Dockerfile
###########################
FROM node:0.12

#Update and add build essentials for compiling node dependencies
RUN apt-get update
RUN apt-get install -y build-essential

#Install php for amp cli
RUN apt-get -y install php5-common php5-cli

#Change node version
RUN npm install -g n
RUN n 0.12.8

#Install Node Global dependencies
RUN npm install -g bower

###############################

Thanks
Simon

**Comment by shinnn** [comment]
This is a `gifsicle-bin` issue. https://github.com/imagemin/gifsicle-bin
